---
title: "Image filter group 6 exam"
author: "Jonas Wuopio"
date: "Sys.Date()"
output: pdf_document
---


```{r "load image and convert to bitmap"}

library(magick)

# Path to the image
image_path <- "C:/Users/jonwuo/OneDrive - Karolinska Institutet/Dokument/Forskning/Kurser/Inermediate R/Group exam/Testimage.jpg"

#load image into environment
image_bitmap <- image_read(image_path)

#Turn jpeg into bitmap 
image_bitmap <- image_bitmap[[1]]

```

```{r "greyscale filter"}

greyscale_filter <- function(rgb) {
  
  #Calculate the greyscale value from the rgb-vector
  greyscale_value <- round(rgb[1] * 0.299 + rgb[2] * 0.587 + rgb[3] * 0.114)
  
  return(as.raw(c(greyscale_value, greyscale_value, greyscale_value)))
}


```

```{r "colour filter"}
#Funtion for two colour-filter
#colour_1 are colour vectors of choice
#red = c(255, 0, 0), green = c(0, 255, 0), blue = c(0, 0, 255). Second colour is set to white = c(255, 255, 255)

two_colour_filter <- function(rgb, colour_1) {

  # Extract RGB values from the input vector
  R <- rgb[1]
  G <- rgb[2]
  B <- rgb[3]
  
  #Calculate the greyscale value from the rgb-vector
  greyscale_value <- round(R * 0.299 + G * 0.587 + B * 0.114)
  
  # Apply the cutoff for two-colour effect
    if (greyscale_value > 127) {
      # colour if greater than cutoff 
      return(as.raw(colour_1))
    }  else {
        # colour if less than cutoff
        return(as.raw(c(255, 255, 255)))    
    }
} 

```


```{r "applying the filter to the image"}

apply_greyscale_filter <- function(image) {

  # Copy of the image to store filtered values
  filtered_image <- image
  
  # Loop through each pixel in the image
  for (row in 1:dim(image)[3]) {
    
      for (col in 1:dim(image)[2]) {
      
        # Extract RGB values for the current pixel
        R <- as.numeric(image[1, col, row])
        G <- as.numeric(image[2, col, row])
        B <- as.numeric(image[3, col, row])
      
        # Apply the greyscale filter function to the RGB-vector
        greyscale_pixel <- greyscale_filter(c(R, G, B))
      
        # Update the filtered bitmap
        filtered_image[1, col, row] <- as.raw(greyscale_pixel[1])
        filtered_image[2, col, row] <- as.raw(greyscale_pixel[2])
        filtered_image[3, col, row] <- as.raw(greyscale_pixel[3])
    }
  }
  return(filtered_image)
}
  
```

```{r}

#Apply filter function. image is a bitmap image and colours are vectors of choice. 

apply_two_colour_filter <- function(image, colour) {

  # Copy of the image to store filtered values
  filtered_image <- image
  
  # Loop through each pixel in the image
  for (row in 1:dim(image)[3]) {
    
      for (col in 1:dim(image)[2]) {
      
        # Extract RGB values for the current pixel
        R <- as.numeric(image[1, col, row])
        G <- as.numeric(image[2, col, row])
        B <- as.numeric(image[3, col, row])
      
        # Apply the two colour filter function to the RGB-vector
        two_colour_pixel <- two_colour_filter(c(R, G, B), colour)
      
        # Update the filtered bitmap
        filtered_image[1, col, row] <- as.raw(two_colour_pixel[1])
        filtered_image[2, col, row] <- as.raw(two_colour_pixel[2])
        filtered_image[3, col, row] <- as.raw(two_colour_pixel[3])
    }
  }
  return(filtered_image)
}
```



```{r}
#Image filter. fun = greyscale for greyscale, colour for colour (colour = colour vector of choice (white is default))

apply_image_filter <- function(image, fun, colour = c(255, 0, 0), ...) {
  
  # Apply greyscale filter
  if (fun == "greyscale") {
    return(apply_greyscale_filter(image))
  }
  
  # Apply two-colour filter
  else (fun == "colour") 
    
    return(apply_two_colour_filter(image, colour, ...))
  } 


  
```

```{r "control the function"}

image_read(apply_image_filter(image_bitmap, fun = "colour", c(0, 0, 0)))

```

